name: randomidea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Adjust this based on your Flutter version requirements

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.8  # For making HTTP requests to OpenAI's API
  flutter_dotenv: ^5.0.2  # To securely manage environment variables
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
